Feature/ob 23 - ftp connection
Worms308/OnBank pull request #18
Opened 2019-07-12 08:17 UTC by PyQIT

2019-07-12 08:26 UTC, Worms308 approved these changes

2019-07-12 08:34 UTC, regularmikey requested changes

2019-07-12 08:34 UTC, regularmikey commented on Backend/src/main/java/com/onbank/ftp/FtpClient.java
> +public class FtpClient {
1. Klasa nazywa się tak samo jak klasa z apache co jest mylące. Zalecam zmianę nazwy naszej wersji
2. Zróbmy z tego component springa

2019-07-12 08:34 UTC, regularmikey commented on Backend/src/test/java/com/onbank/ftp/FtpClientTest.java
> +    void givenRemoteFile_whenDownloading_thenItIsOnTheLocalFilesystem() throws IOException {
Niestety nie rozumiem z nazwy metody co jest celem testu :D. Może powinno być po prostu shouldDownloadFile?

2019-07-12 08:34 UTC, regularmikey commented on Backend/src/test/java/com/onbank/ftp/FtpClientTest.java
> +        assertThat(new File("downloaded_buz.txt")).exists();
Co my tutaj właściwie testujemy? Bo z tego co widzę to nie wykorzystywana jest tutaj żadna metoda naszego klienta

2019-07-15 07:43 UTC, Worms308 approved these changes

2019-07-15 09:19 UTC, regularmikey requested changes

2019-07-15 09:19 UTC, regularmikey commented on Backend/src/main/java/com/onbank/ftp/FtpConnection.java
> +public class FtpConnection {
Nie ma @Component

2019-07-15 09:19 UTC, regularmikey commented on Backend/src/test/java/com/onbank/ftp/FtpClientTest.java
> +    @Value("${onbank.server}")
Jeśli zrobimy component z naszego klienta to nie ma potrzeby deklaracji tych zmiennych w tym miejscu, zostaną one pobrane z propertisów testówych

2019-07-16 06:33 UTC, regularmikey requested changes

2019-07-16 06:33 UTC, regularmikey commented on Backend/src/test/java/com/onbank/ftp/FtpClientTest.java
> +    @BeforeEach
Zmieńmy na beforeAll jeśli ten sam ftp jest używany we wszystkich testach, zaoszczędzi nam to czas

2019-07-16 08:24 UTC, regularmikey requested changes

2019-07-16 08:24 UTC, regularmikey commented on Backend/src/test/java/com/onbank/ftp/FtpClientTest.java
> +        ftpConnection.setServer("localhost");
skoro mamy już propertisy w testach to je wykorzystajmy zamiast wpisywać samemu wartości

2019-07-16 08:37 UTC, regularmikey approved these changes

2019-07-16 08:40 UTC, merged