Feature/ob 26
Worms308/OnBank pull request #37
Opened 2019-07-17 13:47 UTC by PyQIT

2019-07-17 14:32 UTC, Worms308 commented on Backend/src/test/java/com/onbank/api/model/TestTransferToCSV.java
>                  "32324.3,\"32324.3\",\"2019-07-15\",\"Opis operacji\",\"\",\"INSTANT\",\"WAITING\",\"PL32349188939421535264612669\",\"Jan Kowalski\",\"PL32349188939421535264612669\",\"Jan Kowalski\"\
Testy przechodzą mimo, że teraz dane są inne niż obiekt mock?

2019-07-17 14:32 UTC, Worms308 commented on Backend/.idea/libraries/Maven__commons_net_commons_net_3_6.xml
> +  <library name="Maven: commons-net:commons-net:3.6">
Mieliśmy nie zmieniać nic w xml.

2019-07-17 14:32 UTC, Worms308 commented on Backend/.idea/libraries/Maven__org_mockftpserver_MockFtpServer_2_7_1.xml
> +  <library name="Maven: org.mockftpserver:MockFtpServer:2.7.1">
Mieliśmy nie zmieniać nic w xml.

2019-07-18 06:03 UTC, regularmikey requested changes

2019-07-18 06:03 UTC, regularmikey commented on Backend/.idea/libraries/Maven__commons_net_commons_net_3_6.xml
> +  <library name="Maven: commons-net:commons-net:3.6">
Co to jest za plik? Jest nam potrzebny w ogóle w repo?

2019-07-18 06:03 UTC, regularmikey commented on Backend/src/main/java/com/onbank/schedulers/TransferSessions.java
> +        List<Transfer> transfers = transferRepository.findAll().stream()
To do zmiany. Nie filtrujmy w pamięci naszej aplikacji po pobraniu wszystkich rekordów, tylko już w bazie danych. Trzeba zrobić metodę w repo, która wyciągnie nam pola o wymaganych właściwościach

2019-07-18 06:03 UTC, regularmikey commented on Backend/src/main/java/com/onbank/schedulers/TransferSessions.java
> +            TransferToCSV.generateCSV("transferOutcoming.csv", transfers);
transferOutcoming.csv sie powtarza, można  wynieść do stałej

2019-07-18 06:03 UTC, regularmikey commented on Backend/src/main/java/com/onbank/schedulers/TransferSessions.java
> +            if(!Paths.get("csv/incoming").toFile().exists()) {
nazwy folderów też bym wyniósł do stałej żeby w razie ewentualnej zmiany były od razu widoczne

2019-07-18 08:44 UTC, regularmikey requested changes

2019-07-18 08:44 UTC, regularmikey commented on Backend/src/main/java/com/onbank/api/repository/TransferRepository.java
> +    public List<Transfer> findByRealizationStateAndDateAfter(TransferState realizationState, LocalDate firstDate);
public nie potrzebne bo jest domyślne

2019-07-18 08:44 UTC, regularmikey commented on Backend/src/main/java/com/onbank/schedulers/TransferSessions.java
> +                .stream()
Nic już nie musimy streamować bo dostajemy z repo gotową liste

2019-07-18 09:10 UTC, regularmikey approved these changes

2019-07-18 09:18 UTC, Worms308 approved these changes

2019-07-18 09:19 UTC, merged