Feature/ob 33 - odbieranie naglowka http
Worms308/OnBank pull request #40
Opened 2019-07-19 10:57 UTC by Worms308

2019-07-19 11:54 UTC, PyQIT approved these changes

2019-07-19 12:41 UTC, regularmikey requested changes

2019-07-19 12:41 UTC, regularmikey commented on Backend/src/main/java/com/onbank/api/controller/TransferController.java
> +        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
Ta logika nie powinna znajdować się w kontrolerze, kontroler tylko ma za zadanie przygotować dane i przesłać je do serwisu, jeżeli potrzebujesz kontekstu uzytkownika to powinieneś go odebrać już w serwisie

2019-07-22 06:00 UTC, regularmikey requested changes

2019-07-22 06:00 UTC, regularmikey commented on Backend/src/main/java/com/onbank/api/service/implementation/TransferServiceImpl.java
> +        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
Czy w przypadku każdej operacji będziemy zmuszeni do wyciągania kontekstu użytkownika w ten sposób? Jeżeli tak, to żeby uniknąć replikacji proponuje wynieść tę operację do odrębnej klasy z metodą statyczną (jeżeli w ten sposób to zadziała i kontekst się przechowa) bądź do serwisu

2019-07-22 07:17 UTC, regularmikey approved these changes

2019-07-22 07:21 UTC, merged