Feature/ob 6
Worms308/OnBank pull request #9
Opened 2019-07-09 10:17 UTC by PyQIT

2019-07-09 10:22 UTC, regularmikey requested changes

2019-07-09 10:22 UTC, regularmikey commented on Backend/src/main/java/com/onbank/api/model/Transfer.java
> +    private OperationType OperationType;
Dodałbym tutaj adnotacje  @Enumerated(EnumType.STRING) by w bazie zapisala się pełna nazwa a nie liczba porzadkowa enuma

2019-07-09 10:22 UTC, regularmikey commented on Backend/src/main/java/com/onbank/api/transformer/TransferTransformer.java
> +    static public TransferDto convertToDto(Transfer transfer){
public static, wedlug konwencji napierw piszemy modyfikator dostępu

2019-07-09 10:22 UTC, regularmikey commented on Backend/src/test/java/com/onbank/api/controller/TransferControllerTest.java
> +        assertThat(this.transferController.getTransfers()).isEmpty();
Czemu tutaj wywołujemy metodę a niżej strzelamy do api? W tym przypadku też proponuję wykonać strzał do api i sprawdzić, czy w jsonie przychodzi pusta lista

2019-07-09 10:22 UTC, regularmikey commented on Backend/src/test/java/com/onbank/api/controller/TransferControllerTest.java
> +                .andExpect(status().isOk());
nie wiemy czy na pewno json coś nam zwrócił, proszę o uwzględnienie tego w testach

2019-07-09 11:17 UTC, patrykolesinski requested changes
Ten pull request jest do usunięcia, bo ustawiłeś merga na mastera. A powinien być merge na story/OB-1. Nie zastanawiało Cię dlaczego pokazuje tak dużo zmian? :)

2019-07-09 11:33 UTC, patrykolesinski commented on Backend/pom.xml
> +        <model.wraper.version>2.3.5</model.wraper.version>
Używamy gdzieś tego <model.wraper.version> ?

2019-07-09 11:33 UTC, patrykolesinski commented on Backend/src/main/java/com/onbank/DatabaseConfig.java
> +//    private final String costam;
Tak jak mówiłem, powinniśmy wynieść wartości do propertiesów używając adnotacji @Value, podobnie jak to zakomentowane ;)

2019-07-09 11:33 UTC, patrykolesinski commented on Backend/src/test/java/com/onbank/api/controller/TransferControllerTest.java
> +    private TransferController transferController;
Nie powinniśmy wstrzykiwać kontrolera do tego testu. Po to nam jest mockMvc żeby strzelać do API i tak sprawdzać, tak jak Michał napisał. Powinny się tutaj znajdować testy podobne do void getStatusCheck(). A jeśli chcemy sprawdzić czy kontroler zwróci nam listę, to powinniśmy dodać coś do repozytorium w beforeTest. Bo w tej chwili zwróci nam pustą listę.

2019-07-10 05:40 UTC, regularmikey requested changes

2019-07-10 05:40 UTC, regularmikey commented on Backend/src/test/java/com/onbank/api/controller/TransferControllerTest.java
> +    void getStatusCheck() throws Exception {
Nazwa metody testowej jest nic nie mówiąca. Według konwencji powinna być w stylu "shouldReturnTransfers"

2019-07-10 05:40 UTC, regularmikey commented on Backend/src/test/java/com/onbank/api/controller/TransferControllerTest.java
> +class TransferControllerTest {
Nie widzę testu dla odpowiedzi gdzie nie ma transferów

2019-07-10 06:15 UTC, Worms308 commented on Backend/src/main/java/com/onbank/api/model/Transfer.java
> +@Setter
Czemu zmieniono @Data na @Getter i @Setter?

2019-07-10 07:22 UTC, regularmikey approved these changes

2019-07-10 07:24 UTC, Worms308 approved these changes

2019-07-10 07:29 UTC, patrykolesinski approved these changes

2019-07-10 07:29 UTC, merged